teams:
  - yellow
  - pink
  - red
  - orange
  - blue
  - pink
  - purple
  - red
  - yellow
  - green
  - purple
  - blue
  - orange
  - pink
  - green
  - blue
  - orange
  - purple
  - red
  - yellow
  - green
  - orange
  - purple
  - yellow
  - pink
  - green
  - blue
  - red
  - pink
  - purple
  - red
  - green
  - orange
  - yellow
  - purple
  - green
  - yellow
  - blue
  - pink
  - red
  - blue
  - orange

red_players:
  - MarinaMobi
  - OhShado
  - KompotikIvun

orange_players:
  - Kreayshawn
  - kohiko
  - ACCG

yellow_players:
  - N7ghtmare
  - QWQSooqa
  - kasusha

green_players:
  - MotoEkb
  - AmaiMiru
  - Satrinava

blue_players:
  - iGsFT
  - kosssarb
  - YepItsLap

purple_players:
  - b1n4ry
  - uberlie
  - kelrina

pink_bears:
  - ggled_
  - mcowin
  - _jiohh